# Generated by Django 6.1 on 2026-08-14 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50, verbose_name='العملة والشبكة')),
                ('address', models.CharField(max_length=255, verbose_name='عنوان الإيداع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'عنوان إيداع',
                'verbose_name_plural': 'عناوين الإيداع',
            },
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50, verbose_name='العملة')),
                ('amount', models.CharField(max_length=50, verbose_name='المبلغ المودع')),
                ('tx_id', models.CharField(max_length=255, unique=True, verbose_name='رقم العملية (TXID)')),
                ('status', models.CharField(max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإيداع')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'عملية إيداع',
                'verbose_name_plural': 'سجل الإيداعات',
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=190000, max_digits=20, verbose_name='الرصيد المتاح')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'محفظة المستثمر',
                'verbose_name_plural': 'محافظ المستثمرين',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='المبلغ')),
                ('coin', models.CharField(max_length=50, verbose_name='العملة والشبكة')),
                ('wallet_address', models.CharField(max_length=255, verbose_name='عنوان المحفظة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('completed', 'اكتمل التحويل (تم خصم الرصيد)'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('admin_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الرفض (يظهر للمستثمر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'طلب سحب',
                'verbose_name_plural': 'طلبات السحب',
            },
        ),
    ]
