# Generated by Django 6.1 on 2026-08-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='الرصيد المتاح'),
        ),
    ]
