# Generated by Django 6.1 on 2026-08-15 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_userbalance_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص الرسالة للمستثمر')),
                ('amount_required', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المطلوب')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'رسالة تحقيق',
                'verbose_name_plural': 'رسائل التحقيق',
            },
        ),
    ]
