# Generated by Django 6.1 on 2026-08-16 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_feetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuturesTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='BTCUSDT', max_length=20, verbose_name='زوج العملة')),
                ('trade_type', models.CharField(choices=[('long', 'شراء (Long) - صعود'), ('short', 'بيع (Short) - هبوط')], max_length=10, verbose_name='نوع الصفقة')),
                ('margin', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المستثمر')),
                ('leverage', models.IntegerField(default=10, verbose_name='الرافعة المالية (X)')),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='سعر الدخول')),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='سعر الإغلاق')),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الربح/الخسارة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت فتح الصفقة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإغلاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستثمر')),
            ],
            options={
                'verbose_name': 'صفقة عقود آجلة',
                'verbose_name_plural': 'صفقات العقود الآجلة',
            },
        ),
    ]
