# Generated by Django 6.1 on 2026-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_futurestrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbalance',
            name='balance',
        ),
        migrations.AddField(
            model_name='userbalance',
            name='futures_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='رصيد العقود الآجلة'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='spot_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='الرصيد الفوري'),
        ),
    ]
